### ISSUE TITLE
Warning Configuration

### ISSUE THREAD

**Issue by roneydourados** [rrd108/nuxt-api-shield#11]
Helo..... 

My configuration in nuxtconfig:

```json
{
  "nitro": {
    "experimental": {
      "tasks": true
    },
    "scheduledTasks": {
      "*/15 * * * *": [
        "shield:clean"
      ]
    },
    "storage": {
      "shield": {
        "driver": "memory"
      }
    }
  },
  "nuxtApiShield": {
    "errorMessage": "Too Many Requests",
    "limit": {
      "ban": 3600,
      "duration": 108,
      "max": 100
    },
    "log": false,
    "retryAfterHeader": false
  }
}
```

When I run the project, return warning:

 **WARN  Scheduled task shield:clean is not defined!**

**Comment by rrd108** [comment]
What version do you use?

**Comment by rrd108** [comment]
I see what is the problem here. I missed this part from the readme.

You should create your own clean task at `server/tasks/shield/clean.ts`

I added an example in the readme: https://github.com/rrd108/nuxt-api-shield?tab=readme-ov-file#5-create-your-clean-task

**Comment by rrd108** [comment]
I reopened this isseu as I run into a problem related to this.
