### ISSUE TITLE
Cannot create property 'count' on string

### ISSUE THREAD

**Issue by paulvonber** [rrd108/nuxt-api-shield#14]
<img width="830" alt="image" src="https://github.com/user-attachments/assets/df0d2cd3-c691-413a-ae84-cea777adc736">

Running on:
Nuxt: v3.13.0

**Comment by rrd108** [comment]
I was not able to reproduce the error.

Can you give me a reproduction link, or a link to a github repo?

**Comment by rrd108** [comment]
Please check if v0.6.9 solved your problem

**Comment by paulvonber** [comment]
@rrd108 Sorry didn't get back earlier, but yes after update don't see this issue anymore. 
Thanks a lot!

**Comment by rrd108** [comment]
Great 

Thanks for the feedback
