### ISSUE TITLE
How does one use this module?

### ISSUE THREAD

**Issue by danieltamas** [rrd108/nuxt-api-shield#16]
The documentation is incomplete regarding usage.
How does one add it to a server route?

Thanks

**Comment by rrd108** [comment]
Hi Daniel,

You do not have to add it to the server route. from the [README / Quick Setup](https://github.com/rrd108/nuxt-api-shield?tab=readme-ov-file#quick-setup) yo should do step 1-5 and you are done.

Let me know if you have further questions.

**Comment by danieltamas** [comment]
Hey, thanks for getting back. If I were to restrict this to only certain routes, how would one do it?

**Comment by rrd108** [comment]
That is not yet implemented, I created a new issu for this

**Comment by rrd108** [comment]
implemented in https://github.com/rrd108/nuxt-api-shield/releases/tag/v0.7.0
